orbs:
  react: "thefrontside/react@0.2.0"
version: 2.1 #version
workflows:
  push:
    jobs:
      - react/install
      - react/eslint:
          requires:
            - react/install
      - react/test
          requires
            - requires/install
      - react/coverage:
          requires:
            - react/install
